backend:
  name: github
  repo: erasmdif/TlTr       # <— il repo giusto, con maiuscole corrette
  branch: main
  auth_type: token          # <— forza il login con PAT (niente Netlify)
  # NON mettere base_url / site_id

media_folder: "static/uploads"
public_folder: "/TlTr/static/uploads"   # <— importante su GitHub Pages

publish_mode: editorial_workflow

collections:
  - name: homepage
    label: "Avvisi Homepage"
    files:
      - file: "static/moduli/info/info_homepage.txt"
        label: "Info Homepage"
        name: info_homepage
        editor:
          preview: false
        fields:
          - label: Contenuto
            name: body
            widget: markdown
            buttons: [bold, italic, link, bulleted-list, numbered-list, code, heading-one, heading-two, quote]
